<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="CTL-16" name="PractestCases.Test1" tests="1" failures="0" timestamp="19 Jul 2017 13:25:43 GMT" time="16.213" errors="1">
  <testcase name="account_creation_mobile" time="16.213" classname="PractestCases.Test1">
    <error type="java.lang.RuntimeException" message="java.lang.InstantiationException: PractestCases.FundExplorer1">
      <![CDATA[java.lang.RuntimeException: java.lang.InstantiationException: PractestCases.FundExplorer1
	at org.openqa.selenium.support.PageFactory.instantiatePage(PageFactory.java:134)
	at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:64)
	at PractestCases.Test1.account_creation_mobile(Test1.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
Caused by: java.lang.InstantiationException: PractestCases.FundExplorer1
	at java.lang.Class.newInstance(Class.java:427)
	at org.openqa.selenium.support.PageFactory.instantiatePage(PageFactory.java:131)
	... 26 more
Caused by: java.lang.NoSuchMethodException: PractestCases.FundExplorer1.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.newInstance(Class.java:412)
	... 27 more
]]>
    </error>
  </testcase> <!-- account_creation_mobile -->
</testsuite> <!-- PractestCases.Test1 -->
